[package]
name = "leaderboard"
version = "0.1.0"
edition = "2021"

[dependencies]
common = { path = "../common" }

afire.workspace = true
serde_json.workspace = true
serde.workspace = true
uuid.workspace = true
