INSERT INTO histograms
VALUES (
        ?,
        ?,
        ?,
        ?,
        ?,
        ?,
        ?,
        ?,
        ?,
        ?,
        ?,
        ?,
        ?,
        ?,
        ?,
        ?,
        ?,
        ?,
        ?,
        ?,
        ?,
        ?,
        ?,
        ?,
        ?,
        ?,
        ?
    ) ON CONFLICT DO
UPDATE
SET cost_max = excluded.cost_max,
    cost_01 = excluded.cost_01,
    cost_02 = excluded.cost_02,
    cost_03 = excluded.cost_03,
    cost_04 = excluded.cost_04,
    cost_05 = excluded.cost_05,
    cost_06 = excluded.cost_06,
    cost_07 = excluded.cost_07,
    cost_08 = excluded.cost_08,
    cost_09 = excluded.cost_09,
    cost_10 = excluded.cost_10,
    cost_11 = excluded.cost_11,
    cost_12 = excluded.cost_12,
    latency_max = excluded.latency_max,
    latency_01 = excluded.latency_01,
    latency_02 = excluded.latency_02,
    latency_03 = excluded.latency_03,
    latency_04 = excluded.latency_04,
    latency_05 = excluded.latency_05,
    latency_06 = excluded.latency_06,
    latency_07 = excluded.latency_07,
    latency_08 = excluded.latency_08,
    latency_09 = excluded.latency_09,
    latency_10 = excluded.latency_10,
    latency_11 = excluded.latency_11,
    latency_12 = excluded.latency_12;