[target.x86_64-unknown-linux-gnu]
# Adds the directory the executable is in to the dynamic library search path.
# This is needed because thats where the steam api distributable is.
rustflags = ["-C", "link-arg=-Wl,-rpath,$ORIGIN"]
