[package]
name = "common"
version = "0.1.0"
edition = "2021"

[lib]
path = "lib.rs"

[dependencies]
ahash.workspace = true
bincode.workspace = true
nalgebra.workspace = true
once_cell.workspace = true
serde.workspace = true
